### PR TITLE
[generator] Fix the type error when nesting generics.

### PR DESCRIPTION
**Pull request by ipcjs**

### CODE REVIEW

**Comment by tungpham6195** [comment]
hi guys @NicolaVerbeeck @ipcjs , any updates for this one? hope you guys will merge this soon, thanks

**Comment by NicolaVerbeeck** [comment]
I am waiting for @trevorwang for this as the PR jobs are not launching it seems. Also there seems to be a hickup in getting new versions published to pub.dev

@ipcjs could you merge in latest master into this PR so we can hopefully re-trigger the merge checks?

**Comment by ipcjs** [comment]
@NicolaVerbeeck 
In order to re-trigger the merge checks, I submitted some new code.
But this `Labeler / label (pull_request)` check still fails, how can I fix it?

**Comment by NicolaVerbeeck** [comment]
The labeler always fails, no idea what it is or does

**Comment by ipcjs** [comment]
Maybe we can delete [.github/labeler.yml](https://github.com/trevorwang/retrofit.dart/blob/master/.github/labeler.yml)?

**Pull request merged**
