### PR TITLE
Fix API break with dio 4.0.0-prev3

### PR DESCRIPTION
**Pull request by woprandi**
Since dio `4.0.0-prev2`, `data` is now a named parameter of `Options.compose`

https://github.com/flutterchina/dio/commit/9c00b8a6d972e7beae213a7e836831a303efd99f

### CODE REVIEW

**Comment by andoutica** [comment]
You can override Dio version to 4.0.0-prev1 to temporary fix this. 

```
dependency_overrides:
  dio: 4.0.0-prev1
```

**Comment by NicolaChimerapps** [comment]
From what I can see if I run the tests, there are other breaking changes with how the code is generated and we get a dio assert 'Failed assertion: line 573 pos 7: '!(contentType != null && contentTypeInHeader)': You cannot set both contentType param and a content-type header'

**Comment by NicolaChimerapps** [comment]
I believe this to be a bug in Dio that needs to be resolved there. I hope I have some time later to file it. For now, prev2 is NOT compatible in any way with retrofit nullsafety-wip

**Comment by woprandi** [comment]
@NicolaChimerapps I don't get this warning during tests or code gen

**Comment by NicolaChimerapps** [comment]
> @NicolaChimerapps I don't get this warning during tests or code gen

I took your changes (and integrated them in larger change taking in source_gen 1.0.0, but that not influence this) and when I run the example tests I get failures. https://github.com/flutterchina/dio/issues/1091 created

**Comment by NicolaChimerapps** [comment]
Please update to prev3, that should fix example tests

**Pull request merged**
