### PR TITLE
Fix deprecations of `withNullability`

### PR DESCRIPTION
**Pull request by Carapacik**
In analyzer 6.5.0 they remove support for `getDisplayString(withNullability: false)`:
`String getDisplayString` Only non-nullable by default mode is supported.

Analyzer 6.5.0 and higher support Dart ^3.3 and I also update sdk and replace tuple with records

### CODE REVIEW

**Comment by Carapacik** [comment]
@trevorwang plz check it

**Comment by trevorwang** [comment]
@Carapacik  Thanks for the contribution.
Most of things look fine.
Let's move the retrofit to 5.0 and generator to 9.0 due to the breaking change of dart dependency

**Comment by Carapacik** [comment]
I think there is no point in raising the retrofit version, since it will work with the new version of the generator. But the generator can be raised

**Comment by trevorwang** [comment]
@Carapacik  Yes.  You are right. Let's only raise the generator

**Comment by Carapacik** [comment]
@trevorwang I am ready for merge

**Comment by trevorwang** [comment]
Have been published to pub . Thanks the update again!!

**Pull request merged**
