### PR TITLE
Fix deprecated warning with analyzer 5.12.0

### PR DESCRIPTION
**Pull request by Carapacik**

### CODE REVIEW

**Comment by Carapacik** [comment]
Sorry, analyzer ^5.12 support only Dart 2.19 and above

**Comment by Carapacik** [comment]
Should I raise analyzer and Dart for 2.19, or should I leave it at 2.18?

**Comment by Carapacik** [comment]
Problem is due to source_gen ^1.3.0

**Comment by trevorwang** [comment]
It's a BREAKING change.  Let increase the major version and mark it as a pre-relaase one.

**Comment by Carapacik** [comment]
Like retrofit_generator 7.0.0 and analyzer 5.12?

**Comment by Carapacik** [comment]
@trevorwang check now plz

**Pull request merged**
