### PR TITLE
fix: Add handling @MultiPart in codegen

### PR DESCRIPTION
**Pull request by artem-zaitsev**
Codegen had ignored a @MultiPart annotation before this moment.

It is caused problems with multiparts requests.

This PR added a MimeType-interface to FormUrlEncoded and Multipart annotations
``` dart
// An interface for annotation which has mime type.
/// Such as [FormUrlEncoded] and [MultiPart].
abstract class _MimeType {
  abstract final String mime;

  const _MimeType();
}
```

and handling both annotations when generate code.
```dart
ConstantReader? _getContentTypeAnnotation(MethodElement method) {
    final multipart = _getMultipartAnnotation(method);
    final formUrlEncoded = _getFormUrlEncodedAnnotation(method);

    if (multipart != null && formUrlEncoded != null) {
      throw InvalidGenerationSourceError('Two content-type annotation on one request ${method.name}');
    }

    return multipart ?? formUrlEncoded;
  }
```

### CODE REVIEW

**Comment by trevorwang** [comment]
test code please.

**Comment by artem-zaitsev** [comment]
@trevorwang yes, of course - I marked this PR as draft

**Comment by artem-zaitsev** [comment]
@trevorwang I need to change both annotation and generator packages. For passing unit test i need actual(updated) annotations. Should I make two PR's with separate changes?

**Comment by trevorwang** [comment]
yes. please create a PR for annotation first.

**Comment by artem-zaitsev** [comment]
@trevorwang https://github.com/trevorwang/retrofit.dart/pull/437

**Pull request closed without merging**
