### PR TITLE
Support source_gen 1.0.0

### PR DESCRIPTION
**Pull request by NicolaChimerapps**
Note: Pulls in #319

### CODE REVIEW

**Comment by andoutica** [comment]
Hi @trevorwang, can you push this change to pub.dev?

**Comment by trevorwang** [comment]
> Hi @trevorwang, can you push this change to pub.dev?

see 2.0.0-beta2

**Comment by foxanna** [comment]
Hi @trevorwang, thanks for the update! ❤️
For me, https://pub.dev/packages/retrofit still displays `2.0.0-beta1` as the latest version 🤔

**Comment by NicolaChimerapps** [comment]
> Hi @trevorwang, thanks for the update! ❤️
> For me, https://pub.dev/packages/retrofit still displays `2.0.0-beta1` as the latest version 🤔

retrofit-generator is updated to beta2, retrofit itself did not need a bump

**Comment by trevorwang** [comment]
There are only changes for generator.

So please keep using the previous version of retrofit.

**Pull request merged**
