### PR TITLE
Use Flutter compute for parsing models

### PR DESCRIPTION
**Pull request by via-guy**
Following #164, I suggest a solution for using Flutter's `compute` function. It requires users to define a top-level function (like for any Isolate, basically).

I'll probably need some help with this solution, and it depends on #407 being passed first, since it needs a new Parser enum value to be defined.

We should also pass #406 first too, since it will remove a lot of noise for code formatting.

### CODE REVIEW

**Comment by via-guy** [comment]
Once #412 is merged and retrofit 3.0.0 is released, the tests should be able to run and pass.

**Comment by via-guy** [comment]
@trevorwang ok, I think I'm finally ready for review. I had to make a change to handle `List`s as spawning an isolate per element was a crazy bad idea, but it makes the usage a bit more bulky. There's probably a way to automate the list functions, but I'd rather save that for a future improvement.

From testing with my app, even just spawning 1 isolate is soooo slow. I can't believe how poorly Flutter/Dart handles this :(

**Comment by via-guy** [comment]
I was wrong. I broke something.

**Comment by trevorwang** [comment]
Everything looks well, can you update 
https://github.com/trevorwang/retrofit.dart/blob/cbfef434de1a0d94f5c79e0b770dcf1b3f0feb1b/generator/CHANGELOG.md?plain=1#L1
accordingly?

**Pull request merged**
