### PR TITLE
[wip] Define a new parser annotation for using the Flutter compute function

### PR DESCRIPTION
**Pull request by via-guy**
Following #164, I would like to try another solution. This needs to be merged first before we can commit #408, as it requires bumping up the package version.

### CODE REVIEW

**Comment by trevorwang** [comment]
let me know when it is ready for merge.

**Comment by via-guy** [comment]
> let me know when it is ready for merge.

First I need to know if #408 makes sense. Is this a solution that we want?

**Comment by trevorwang** [comment]
> > let me know when it is ready for merge.
> 
> First I need to know if #408 makes sense. Is this a solution that we want?

Let's use it until we have a better solution.

**Comment by via-guy** [comment]
OK. But didn't we want to update the version to 2.3.0, since it's a breaking change?

**Comment by trevorwang** [comment]
Yes.

Please use version 3.0.0  and update the CHAGNELOG file accordingly.

**Pull request merged**
