### PR TITLE
Fix/enum return types and query params

### LINKED ISSUE #588: Serialize Enum type as name
**Is your feature request related to a problem? Please describe.**
Currently, If I use Enum type as `@Query` parameter. It is generated with `.toJson()` method. Which is fine as long as I can use the extension function. But If retrofit supports enum type. It would be more convenient.

**Describe the solution you'd like**
The solution should pass this test case If the enum type doesn't have `@JsonEnum(fieldRename: FieldRename.screamingSnake)`. 
I tried to implement it. But currently, I have no idea how to check if DartType is an enum.
```
enum EnumParam {
  enabled, disabled,
}

@ShouldGenerate(
  '''
    final queryParameters = <String, dynamic>{r'test': status?.name};
''',
  contains: true,
)
@RestApi()
abstract class TestQueryParamEnum {
  @GET('/test')
  Future<void> getTest(@Query('test') EnumParam? status);
}
```

**Describe alternatives you've considered**
Currently, I'm using the extension function.

```
extension EnumToJson on Enum {
  String toJson() => name;
}
```

**Additional context**
If `@JsonEnum(fieldRename: FieldRename.screamingSnake)` used. We have to generate a map

```
const _$EnumParam = {
  EnumParam.enabled: 'ENABLED',
  EnumParam.disabled: 'DISABLED',
};

final queryParameters = <String, dynamic>{r'test': _$EnumParam?[status]};
```

### PR DESCRIPTION
**Pull request by elenaferr0**
fix #588 and #591
not 100% sure that `dartType.element is EnumElement` is the best way to check if a type is an enum (`dartType.isDartCoreEnum` does not work in this case). Just let me know if there's another way please.

edit: i also found the open issues  #559 and #536 that would be fixed by this pr

### CODE REVIEW

**Comment by trevorwang** [comment]
Great work. Thanks for the contribution.

**Comment by lian-cc** [comment]
Hi, I have a question about this.
How should I use the json value on the query parameter after the change?
Thanks.

**Comment by elenaferr0** [comment]
> Hi, I have a question about this. How should I use the json value on the query parameter after the change? Thanks.

Hi, I'm not sure I got your question, I'll try to explain then if you still have doubts feel free to ask.
The only difference is how the enum is serialized and deserialized, it should not impact your use of the retrofit generated classes.
Previously, you had to include a `toJson` method in your enums to be able to convert your enum value to its corresponding string, i.e. if you had
```dart
enum Status { on, off }
```
You would typically have to create a map between these enum values and their corresponding string values ("on" and "off" in this case), and then use it in your `toJson` method. This is unnecessary since Dart offers `Enum.name` which automatically gives you the string corresponding to your enum value.
When converting back string values to its corresponding enum value instead, there was a bug in `retrofit_generation` (now fixed by this pr) and `.fromJson` method was called on enums in order to deserialize them. In that situation, what is done now is iterating through enum values, until one with the same name as the string you want to convert to enum is found. Otherwise it just throws an error.
Don't know if this clarifies your doubts

**Comment by lian-cc** [comment]
My question has been resolved with #596, thanks a lot.

**Pull request merged**
