### PR TITLE
Fix generic argument factories support

### LINKED ISSUE #627: Extend Retrofit & Freezed Serialization with Custom fromJson for Generic Types
**Is your feature request related to a problem? Please describe.**
Yes, when using Retrofit along with Freezed in Flutter, I am facing a challenge with handling generic types in my API response model. Specifically, I am unable to provide a custom `fromJson` method for a generic type when deserializing the JSON response. This becomes a bottleneck when trying to automate the serialization/deserialization process for various data models.

```dart
// Example of the API response model
@Freezed(genericArgumentFactories: true)
class ApiResponseModel<T> with _$ApiResponseModel<T> {
  const factory ApiResponseModel({
    @JsonKey(name: 'data') T? data,
  }) = _ApiResponseModel<T>;

  factory ApiResponseModel.fromJson(Map<String, dynamic> json, T Function(Object? json) fromJsonT) =>
      _$ApiResponseModelFromJson(json, fromJsonT);
}
```

**Describe the solution you'd like**
I would appreciate an option in Retrofit to specify a custom `fromJson` method for generic types on a per-method basis. This could be done by introducing a new annotation that can be used alongside `@GET`, `@POST`, etc., to specify the `fromJson` function for the generic type.

```dart
// Desired usage with Retrofit
@RestApi()
abstract class MyApi {
  @POST('/endpoint')
  @JsonFunc(fromJsonFunc: myCustomFromJson)
  Future<ApiResponseModel<MyModel>> fetchData();
  ...
}
```

**Describe alternatives you've considered**
I have considered creating custom converters for each data type, but this approach is not scalable and leads to a lot of boilerplate code. Also, I tried using mixins and factory constructors, but these solutions do not integrate well with Retrofit and Freezed, and make the code more complex.

**Additional context**
Handling generic types efficiently is crucial for reducing boilerplate and making the code more maintainable, especially in larger projects with many data models and API endpoints. Providing a way to specify the `fromJson` method on a per-method basis would allow for greater flexibility and ease of use when working with Retrofit and Freezed in Flutter projects.

### PR DESCRIPTION
**Pull request by TekExplorer**
fix #627

### CODE REVIEW

**Comment by TekExplorer** [comment]
Note: i do not know if this works with multiple generics

**Comment by TekExplorer** [comment]
For those of you who want to test this directly, you can specify the following in your dev dependencies (for as long as the branch exists)
```yaml
  retrofit_generator:
    git: 
      url: https://github.com/TekExplorer/retrofit.dart
      ref: TekExplorer/expand-from-json
      path: generator/
```

**Comment by TekExplorer** [comment]
@trevorwang Please review this PR - I need this to work

**Comment by trevorwang** [comment]
Thanks for the contribution

**Pull request merged**
