### PR TITLE
修复Bean嵌套过程中不能使用Map接受的场景，因为生成Bean的过程中全部使用了.fromJson进行转换。

### PR DESCRIPTION
**Pull request by WizzXu**
本次修改增加了使用'Map<'做匹配兼容Map接收的场景，如果匹配到Map使用.from接收

### CODE REVIEW

**Comment by ipcjs** [comment]
There seems to be a lot of indentation changes in the code? Did you turn on the code formatting function?

**Comment by WizzXu** [comment]
> There seems to be a lot of indentation changes in the code? Did you turn on the code formatting function?

Yes, my code is formatted automatically. My ide is Androidstudio.

**Comment by WizzXu** [comment]
> There seems to be a lot of indentation changes in the code? Did you turn on the code formatting function?

Yes, my code is formatted automatically. My ide is Androidstudio.

**Comment by ipcjs** [comment]
A large number of code format changes make it difficult to review the code.
You should probably turn off code formatting and submit only the parts you modified.

**Comment by ipcjs** [comment]
（艹，Google翻译好烂！）

几点修改建议：
1. 使用自动格式化后，代码修改的行数太多，Review不方便。建议关闭自动格式化，只把你修改的部分提交上来。
2. 这个仓库的commit info、issue等都是用的英文，建议也尽量用英文（或者像我一样用Google翻译🙄）
3. 看样子似乎修改了generator？这个代码生成器上千行代码挤在一起，实在是很难维护😵，改generator一定要把对应的test写了

关于代码格式，我觉得要 @trevorwang 来搞，是80列宽还是120列宽，统一格式化下所有代码。

**Comment by trevorwang** [comment]
Thanks for the suggestion from  @ipcjs 

Please use `dart fmt` to format code if a customized format style is set in your IDE.

**Pull request closed without merging**
