### PR TITLE
Feat: Enable passing in Extras using Custom Annotations

### PR DESCRIPTION
**Pull request by farmery**
### Summary
This PR adds functionality that allows developers to pass extras with requests using custom classes.

### Problem
Imagine you want every request in your app to include some additional metadata, such as an id and a region. Without this feature, you would have to annotate each request manually with something like Extra({'id': '1234', 'region': 'ng'}). While this approach works, it requires passing the key-value pairs each time, which introduces several risks:

Developers may inadvertently misspell a key (e.g., regoin instead of region).
A required key might be forgotten or omitted.
The repeated manual input increases the chance of inconsistency,

### Solution
Introduce `TypedExtras`, which developers can extend to provide extras in a structured and type-safe manner. By defining fields within the custom class, developers can avoid manual key-value entry, ensuring consistency and reducing the risk of errors.

Example: 
```dart
class MetaData extend TypedExtras {
 final String id;
 final String region;
 const MetaData({required this.id, required region});
}

@MetaData(
  id: '1234',
  region: 'ng',
)
@GET("/get")
Future<String> fetchData(@Extras() Map<String, dynamic> extras);

// Which will generate 
final _extras = <String, dynamic>{
 'id': '1234',
 'region': 'ng',
}
```

### CODE REVIEW

**Comment by trevorwang** [comment]
Hi @farmery , thanks for the great work.


Lets bump the lib versions and update the change logs before we merge that changes.

**Comment by farmery** [comment]
Hi @trevorwang  I just updated the change logs and versions

**Comment by moshe5745** [comment]
@farmery What a timing! 
I came to implement some features in our app by passing headers and deleting them in the interceptor.
Came to the changelog and see this... Thank you very much!

@trevorwang Could you copy-paste the example provided here to the docs?

**Comment by moshe5745** [comment]
@farmery 
Is it possible to use `TypedExtras` only for typing without the default value?
I mean I have some API endpoint. I want the extras to be typed.
Right now when I extract them in the interceptor I have Map<String, dynamic>. Is it possible to infer the type somehow? Or is it a feature on the Dio side?

**Comment by trevorwang** [comment]
> @farmery What a timing! I came to implement some features in our app by passing headers and deleting them in the interceptor. Came to the changelog and see this... Thank you very much!
> 
> @trevorwang Could you copy-paste the example provided here to the docs?

Would you like to submit a PR for this? @moshe5745

**Comment by moshe5745** [comment]
> > @farmery What a timing! I came to implement some features in our app by passing headers and deleting them in the interceptor. Came to the changelog and see this... Thank you very much!
> > @trevorwang Could you copy-paste the example provided here to the docs?
> 
> Would you like to submit a PR for this? @moshe5745

Sure

**Pull request merged**
