### PR TITLE
Adds support for analyzer: ^0.40.0

### LINKED ISSUE #252: retrofit generator incompatible with build runner 1.10.3: version solving failed
when running pub get with retrofit generator and build runner, some versions are colliding.
these are the versions i have:
retrofit: ^1.3.4
retrofit_generator: ^1.3.8+2
build_runner: ^1.10.3

this is the error:
```
Because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer ^0.40.1, build_runner >=1.10.3 requires analyzer ^0.40.1.

And because retrofit_generator 1.3.8+2 depends on analyzer <=0.39.17 and no versions of retrofit_generator match >1.3.8+2 <2.0.0, build_runner >=1.10.3 is incompatible with retrofit_generator ^1.3.8+2.
```

### PR DESCRIPTION
**Pull request by TheMisir**
Fixes #252

### CODE REVIEW

**Comment by trevorwang** [comment]
@TheMisir  Please mark sure the changes can pass the CI checks.

**Comment by TheMisir** [comment]
> @TheMisir Please mark sure the changes can pass the CI checks.

Ok, I will fix it today or tomorrow maybe.

**Comment by TheMisir** [comment]
@trevorwang 

I think CI error caused by json_serializable. [job 872](https://app.circleci.com/pipelines/github/trevorwang/retrofit.dart/537/workflows/083e9a4b-9ea2-42a9-8bd5-6d9768265a77/jobs/872)

```
NoSuchMethodError: The getter 'definingUnit' was called on null.
Receiver: null
Tried calling: definingUnit
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:142:28)
#2      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:97:27)
#3      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:537:25)
#4      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:577:36)
#5      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:130:5)
#6      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:12)
#7      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1286:63)
#8      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#9      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1263:20)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216:14)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1215:40)
#17     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:552:41)
#18     AnalyzerResolver._syntacticErrorsFor (package:build_resolvers/src/resolver.dart:216:36)
#19     AnalyzerResolver.libraryFor (package:build_resolvers/src/resolver.dart:186:28)
<asynchronous suspension>
#20     PerActionResolver.libraryFor (package:build_resolvers/src/resolver.dart:109:22)
<asynchronous suspension>
#21     _DelayedResolver.libraryFor (package:build/src/builder/build_step_impl.dart:213:12)
<asynchronous suspension>
#22     BuildStepImpl.inputLibrary (package:build/src/builder/build_step_impl.dart:38:21)
#23     _Builder.build (package:source_gen/src/builder.dart:70:33)
<asynchronous suspension>
#24     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#25     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#26     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#27     Future.wait (dart:async/future.dart:406:26)
#28     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _runZoned (dart:async/zone.dart:1630:10)
#32     runZonedGuarded (dart:async/zone.dart:1618:12)
#33     runZoned (dart:async/zone.dart:1547:12)
#34     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
#35     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#36     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
#37     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#38     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
<asynchronous suspension>
#39     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#40     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#41     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
#42     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#43     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
#44     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#45     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#46     Future.wait (dart:async/future.dart:406:26)
#47     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#48     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#49     _rootRunUnary (dart:async/zone.dart:1198:47)
#50     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#51     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#53     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#54     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#55     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#56     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#57     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#58     _rootRunUnary (dart:async/zone.dart:1198:47)
#59     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#62     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#63     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#64     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#65     _rootRunUnary (dart:async/zone.dart:1198:47)
#66     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#67     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#68     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#69     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#70     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#71     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#72     _rootRun (dart:async/zone.dart:1190:13)
#73     _CustomZone.run (dart:async/zone.dart:1093:19)
#74     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#75     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#76     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by MahdiPishguy** [comment]
@TheMisir since 3 4 days a go i can't build release from our application :D

**Comment by trevorwang** [comment]
> @TheMisir since 3 or 4 days a go i can't build release from our application :D

lower analyzer to 0.39.17 as a workaround. The latest analyzer support is under development.

**Comment by trevorwang** [comment]
> @trevorwang
> 
> I think CI error caused by json_serializable. [job 872](https://app.circleci.com/pipelines/github/trevorwang/retrofit.dart/537/workflows/083e9a4b-9ea2-42a9-8bd5-6d9768265a77/jobs/872)
> 
> ```
> NoSuchMethodError: The getter 'definingUnit' was called on null.
> Receiver: null
> Tried calling: definingUnit
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:142:28)
> #2      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:97:27)
> #3      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:537:25)
> #4      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:577:36)
> #5      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:130:5)
> #6      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:12)
> #7      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1286:63)
> #8      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
> #9      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1263:20)
> #10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216:14)
> #11     _rootRun (dart:async/zone.dart:1190:13)
> #12     _CustomZone.run (dart:async/zone.dart:1093:19)
> #13     _runZoned (dart:async/zone.dart:1630:10)
> #14     runZoned (dart:async/zone.dart:1550:10)
> #15     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
> #16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1215:40)
> #17     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:552:41)
> #18     AnalyzerResolver._syntacticErrorsFor (package:build_resolvers/src/resolver.dart:216:36)
> #19     AnalyzerResolver.libraryFor (package:build_resolvers/src/resolver.dart:186:28)
> <asynchronous suspension>
> #20     PerActionResolver.libraryFor (package:build_resolvers/src/resolver.dart:109:22)
> <asynchronous suspension>
> #21     _DelayedResolver.libraryFor (package:build/src/builder/build_step_impl.dart:213:12)
> <asynchronous suspension>
> #22     BuildStepImpl.inputLibrary (package:build/src/builder/build_step_impl.dart:38:21)
> #23     _Builder.build (package:source_gen/src/builder.dart:70:33)
> <asynchronous suspension>
> #24     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
> #25     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
> #26     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
> #27     Future.wait (dart:async/future.dart:406:26)
> #28     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
> #29     _rootRun (dart:async/zone.dart:1190:13)
> #30     _CustomZone.run (dart:async/zone.dart:1093:19)
> #31     _runZoned (dart:async/zone.dart:1630:10)
> #32     runZonedGuarded (dart:async/zone.dart:1618:12)
> #33     runZoned (dart:async/zone.dart:1547:12)
> #34     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
> #35     runBuilder (package:build/src/generate/run_builder.dart:61:9)
> #36     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
> #37     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
> #38     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
> <asynchronous suspension>
> #39     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
> #40     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
> #41     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
> #42     Pool.withResource (package:pool/pool.dart:127:28)
> <asynchronous suspension>
> #43     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
> #44     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
> #45     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
> #46     Future.wait (dart:async/future.dart:406:26)
> #47     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
> #48     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
> #49     _rootRunUnary (dart:async/zone.dart:1198:47)
> #50     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #51     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #53     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #54     Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #55     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
> #56     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
> #57     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
> #58     _rootRunUnary (dart:async/zone.dart:1198:47)
> #59     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #60     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #62     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #63     Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #64     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
> #65     _rootRunUnary (dart:async/zone.dart:1198:47)
> #66     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #67     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #68     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #69     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #70     Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #71     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
> #72     _rootRun (dart:async/zone.dart:1190:13)
> #73     _CustomZone.run (dart:async/zone.dart:1093:19)
> #74     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> #75     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> #76     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
> #79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
> ```

1. Please make sure that you can pass the test by execute `pub run test` in generator directory.
2. dartmapper depends on a lower analyzer. I will move dart-json-mapper to a separate project. So then please check all test from example project can work well.

**Comment by TheMisir** [comment]
> 1. Please make sure that you can pass the test by execute pub run test in generator directory.
> 2. dartmapper depends on a lower analyzer. Please move dart-json-mapper to a separate project. So then please check all test from example project can work well.

Thanks. I'll do it today.

**Comment by TheMisir** [comment]
@trevorwang  What was previously minimum supported analyzer version?

**Comment by TheMisir** [comment]
Could you re-run dart 2.9 [workflow](https://app.circleci.com/pipelines/github/trevorwang/retrofit.dart/541/workflows/82cf2a61-b150-4a20-b555-92d0ae190a7a/jobs/887). I think it failed due to internal dart error. Btw I managed to make sure the package works for bot previous and new analyzer versions.

**Comment by TheMisir** [comment]
For some reasons dart 2.9 fails to load tests file. I'm not sure if this was related to the analyzer version change. Because the tests passed on older and newer versions of dart expect 2.9.

**Comment by TheMisir** [comment]
I'm not sure but I think the issue might be related to https://github.com/flutter/flutter/issues/63556 . Which minimum version of analyzer would you suggest? (I managed to make sure the code works for both ^0.40.0 and <0.40.0. Now I just need to find minimum working analyzer version).

**Comment by trevorwang** [comment]
My suggestion is that we use 0.40 as the minimum version. The former version can be used for users who use the SDK lower than 2.9.

Please mark this as a BREAK CHANGE.   And set the generator version to 1.4.0.

Meanwhile, please update README and Changelog accordingly.

**Comment by TheMisir** [comment]
@trevorwang  setting analyzer version to "any" worked. I think the minimum version I set (which is 0.39.0) were not compatible with dart 2.9. Currently the package is compatible with both old and new version of analyzer.

**Comment by TheMisir** [comment]
Btw labeler github action doesn't works for PRs created by non-maintainers. I think there were permission related issues.

**Comment by MahdiPishguy** [comment]
@TheMisir i still have this problem

```yml
environment:
  sdk: '>=2.10.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  ...

  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  retrofit: ^1.3.4+1

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0

  hive_generator: ^0.8.1
  retrofit_generator: any

  lint: ^1.3.0

dependency_overrides:
  analyzer: any
```

**Comment by TheMisir** [comment]
> @TheMisir i still have this problem
> 
> ```yaml
> environment:
>   sdk: '>=2.10.1 <3.0.0'
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   cupertino_icons: ^1.0.0
> 
>   ...
> 
>   dio: ^3.0.10
>   dio_http_cache: ^0.2.11
>   retrofit: ^1.3.4+1
> 
> dev_dependencies:
>   build_runner: ^1.10.3
>   json_serializable: ^3.5.0
> 
>   hive_generator: ^0.8.1
>   retrofit_generator: any
> 
>   lint: ^1.3.0
> 
> dependency_overrides:
>   analyzer: any
> ```

The update haven't been published yet. You can use `analyzer: 0.39.17` which works with latest published retrofit version.

**Comment by MahdiPishguy** [comment]
@TheMisir this version of `analyzer` doesn't work too and i get another error on `dart` classes 

> 
> The update haven't been published yet. You can use `analyzer: 0.39.17` which works with latest published retrofit version.

**Comment by trevorwang** [comment]
> @trevorwang setting analyzer version to "any" worked. I think the minimum version I set (which is 0.39.0) were not compatible with dart 2.9. Currently the package is compatible with both old and new version of analyzer.

If we set a dependency as any in pubspec.yml, it means we have to support all versions of that lib. Obviously, it's not.

Probably, I will publish a new release which only supports dart 2.9 and later with analyzer 0.40 .

Thanks for your contribution.

**Comment by jesseframework** [comment]
setting analyzer version to "any" does not work for me. My environment:
  sdk: ">=2.10.1 <3.0.0"

**Comment by trevorwang** [comment]
generator 4.0 needs sdk >=2.14
 use generator 3.x instead

**Pull request merged**
