### PR TITLE
[WIP]Feature/Nullsafety

### PR DESCRIPTION
**Pull request by NicolaChimerapps**
Initial attempt at adding nullsafety support to the retrofit generator

### CODE REVIEW

**Comment by trevorwang** [comment]
Hi @NicolaChimerapps , thanks for your great contribution.

Please update the unit tests accordingly and make sure all the test cases pass

**Comment by NicolaChimerapps** [comment]
Please note that this is PR is WIP.

**Comment by NicolaChimerapps** [comment]
I have fixed the generator tests with the updated generator.

**Comment by vanlooverenkoen** [comment]
When you configured a baseUrl on your dio instance but the baseUrl is not used in retrofit, the baseUrl empty. Because right now the generator will only look at the retrofit.baseUrl and will not default to the dio.options.baseUrl.

```
  @override
  Future<List<Todo>> getTodos() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<List<dynamic>>(RequestOptions(
        method: 'GET',
        headers: <String, dynamic>{},
        extra: _extra,
        baseUrl: baseUrl,
        // baseUrl: baseUrl ?? _dio.options.baseUrl, -> SHOULD BE GENERATED LIKE THIS
        queryParameters: queryParameters,
        path: '/todos',
        data: _data));
    var value = _result.data!
        .map((dynamic i) => Todo.fromJson(i as Map<String, dynamic>))
        .toList();
    return value;
  }
```

**Comment by NicolaChimerapps** [comment]
As @vanlooverenkoen said, don't use this. I will have to rewrite the rewrite to fix these options issue. Tomorrow probably

**Comment by vanlooverenkoen** [comment]
New changes are working fine! 🎉

**Comment by saharvx9** [comment]
Is there any progress ? 
pls update this library :(

**Comment by vanlooverenkoen** [comment]
> Is there any progress ? 
> pls update this library :(

Last commit is working fine. The tests should be fixed by @trevorwang

**Comment by saharvx9** [comment]
@vanlooverenkoen 
when I am trying this at pubspec its not working :(
 ```
 retrofit:
    git: git://github.com/trevorwang/retrofit.git
```

**Comment by vanlooverenkoen** [comment]
```
dependencies:
  retrofit: ^1.3.4+1

dev_dependencies:
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation
```

**Comment by vanlooverenkoen** [comment]
```
dependencies:
  retrofit: ^1.3.4+1

dev_dependencies:
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation
```

**Comment by NicolaChimerapps** [comment]
@trevorwang I can't see why the tests on CircleCI are failing, the unit tests run fine locally. Only the dartmapper example does not compile due to too many outdated dependencies

**Comment by andoutica** [comment]
any updates on this? I've still been waiting for sound null-safety support :(

**Comment by vanlooverenkoen** [comment]
@trevorwang any idea how we should fix these texts? 
for the labeler pull request job we get
```
Resource not accessible by integration
```

**Comment by andoutica** [comment]
> This is what I am using right now
> 
> ```
> dependencies:
>   retrofit: ^1.3.4+1
> 
> dev_dependencies:
>   retrofit_generator:
>     git:
>       url: https://github.com/Chimerapps/retrofit.dart
>       ref: feature/nullabilitysafe
>       path: generator
> 
> dependency_overrides:
>   retrofit:
>     git:
>       url: https://github.com/Chimerapps/retrofit.dart
>       ref: feature/nullabilitysafe
>       path: annotation
> ```


HI @NicolaChimerapps, I received an incompatible error when upgrading build_runner to 1.12.1 today, can you help me to fix? 

Because every version of retrofit_generator from git depends on build ^1.6.3 and build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0, retrofit_generator from git is incompatible with build_runner >=1.12.0.

**Comment by NicolaChimerapps** [comment]
> > This is what I am using right now
> > ```
> > dependencies:
> >   retrofit: ^1.3.4+1
> > 
> > dev_dependencies:
> >   retrofit_generator:
> >     git:
> >       url: https://github.com/Chimerapps/retrofit.dart
> >       ref: feature/nullabilitysafe
> >       path: generator
> > 
> > dependency_overrides:
> >   retrofit:
> >     git:
> >       url: https://github.com/Chimerapps/retrofit.dart
> >       ref: feature/nullabilitysafe
> >       path: annotation
> > ```
> 
> HI @NicolaChimerapps, I received an incompatible error when upgrading build_runner to 1.12.1 today, can you help me to fix?
> 
> `Because every version of retrofit_generator from git depends on build ^1.6.3 and build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0, retrofit_generator from git is incompatible with build_runner >=1.12.0. `

source_gen is currently incompatible with build >= 2.0.0 due to breaking changes in build. You cannot use this combination for now. You will need to keep your build_runner at a lower version (1.11.x seems to work)

**Comment by trevorwang** [comment]
> @trevorwang any idea how we should fix these tests?
> for the labeler pull request job we get
> 
> ```
> Resource not accessible by integration
> ```

Sorry for the late reply.  I have a lot of work recently.

**Comment by vanlooverenkoen** [comment]
@trevorwang there are still some tests that are failing.

The labeler pr still has the same issue. 
```
Resource not accessible by integration
```

**Comment by trevorwang** [comment]
> @trevorwang there are still some tests that are failing.
> 
> The labeler pr still has the same issue.
> 
> ```
> Resource not accessible by integration
> ```

Labler is not required, just ignore it.

**Comment by vanlooverenkoen** [comment]
We can't see the circle ci logs. So we have no idea why the tests are failing

**Comment by trevorwang** [comment]
```
build 1.6.3 (2.0.0 available)
  build_resolvers 1.5.4 (2.0.0 available)
  build_test 1.3.7 (2.0.0 available)
  graphs 0.2.0 (1.0.0 available)
  resource 2.1.7 (discontinued)
  source_gen 0.9.10+3 (0.9.10+4 available)
Warning: You are using these overridden dependencies:
! retrofit 1.3.4+1 from path ../annotation
Got dependencies!
00:00 +0: loading test/generator_test.dart00:01                                                                                                                                                        +0: loading test/generator_test.dart                                                                                                                                                             lib/src/generator.dart:652:38: Warning: Operand of null-aware operation '?.' has type 'ConstantReader' which excludes null.
 - 'ConstantReader' is from 'package:source_gen/src/constants/reader.dart' ('../../.pub-cache/hosted/pub.dartlang.org/source_gen-0.9.10+3/lib/src/constants/reader.dart').
          genericArgumentFactories = obj?.boolValue ?? false;
                                     ^
00:02 +0: loading test/generator_test.dart00:03                                                                                                                                                        +0: loading test/generator_test.dart00:04                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0 -1: loading test/generator_test.dart [E]                                                                                                                                                      
  Failed to load "test/generator_test.dart":
  Unable to spawn isolate: Error: Cannot run with sound null safety, because the following dependencies
  don't support null safety:
  
   - package:source_gen_test
   - package:build
   - package:code_builder
   - package:dart_style
   - package:source_gen
   - package:build_test
   - package:build_resolvers
   - package:graphs
  
  For solutions, see https://dart.dev/go/unsound-null-safety
00:05 +0 -1: Some tests failed.                                                                                                                                                                        

```

**Comment by NicolaChimerapps** [comment]
Right

> ```
> build 1.6.3 (2.0.0 available)
>   build_resolvers 1.5.4 (2.0.0 available)
>   build_test 1.3.7 (2.0.0 available)
>   graphs 0.2.0 (1.0.0 available)
>   resource 2.1.7 (discontinued)
>   source_gen 0.9.10+3 (0.9.10+4 available)
> Warning: You are using these overridden dependencies:
> ! retrofit 1.3.4+1 from path ../annotation
> Got dependencies!
> 00:00 +0: loading test/generator_test.dart00:01                                                                                                                                                        +0: loading test/generator_test.dart                                                                                                                                                             lib/src/generator.dart:652:38: Warning: Operand of null-aware operation '?.' has type 'ConstantReader' which excludes null.
>  - 'ConstantReader' is from 'package:source_gen/src/constants/reader.dart' ('../../.pub-cache/hosted/pub.dartlang.org/source_gen-0.9.10+3/lib/src/constants/reader.dart').
>           genericArgumentFactories = obj?.boolValue ?? false;
>                                      ^
> 00:02 +0: loading test/generator_test.dart00:03                                                                                                                                                        +0: loading test/generator_test.dart00:04                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0 -1: loading test/generator_test.dart [E]                                                                                                                                                      
>   Failed to load "test/generator_test.dart":
>   Unable to spawn isolate: Error: Cannot run with sound null safety, because the following dependencies
>   don't support null safety:
>   
>    - package:source_gen_test
>    - package:build
>    - package:code_builder
>    - package:dart_style
>    - package:source_gen
>    - package:build_test
>    - package:build_resolvers
>    - package:graphs
>   
>   For solutions, see https://dart.dev/go/unsound-null-safety
> 00:05 +0 -1: Some tests failed.                                                                                                                                                                        
> ```

Right, since source_gen is not nullsafe yet, blocked on x-y-z. The generator has to be run using `--no-sound-null-safety`. This is reflected in the test files I committed, but perhaps there is some hidden config on circleci

**Comment by trevorwang** [comment]
> Right
> 
> > ```
> > build 1.6.3 (2.0.0 available)
> >   build_resolvers 1.5.4 (2.0.0 available)
> >   build_test 1.3.7 (2.0.0 available)
> >   graphs 0.2.0 (1.0.0 available)
> >   resource 2.1.7 (discontinued)
> >   source_gen 0.9.10+3 (0.9.10+4 available)
> > Warning: You are using these overridden dependencies:
> > ! retrofit 1.3.4+1 from path ../annotation
> > Got dependencies!
> > 00:00 +0: loading test/generator_test.dart00:01                                                                                                                                                        +0: loading test/generator_test.dart                                                                                                                                                             lib/src/generator.dart:652:38: Warning: Operand of null-aware operation '?.' has type 'ConstantReader' which excludes null.
> >  - 'ConstantReader' is from 'package:source_gen/src/constants/reader.dart' ('../../.pub-cache/hosted/pub.dartlang.org/source_gen-0.9.10+3/lib/src/constants/reader.dart').
> >           genericArgumentFactories = obj?.boolValue ?? false;
> >                                      ^
> > 00:02 +0: loading test/generator_test.dart00:03                                                                                                                                                        +0: loading test/generator_test.dart00:04                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0: loading test/generator_test.dart00:05                                                                                                                                                        +0 -1: loading test/generator_test.dart [E]                                                                                                                                                      
> >   Failed to load "test/generator_test.dart":
> >   Unable to spawn isolate: Error: Cannot run with sound null safety, because the following dependencies
> >   don't support null safety:
> >   
> >    - package:source_gen_test
> >    - package:build
> >    - package:code_builder
> >    - package:dart_style
> >    - package:source_gen
> >    - package:build_test
> >    - package:build_resolvers
> >    - package:graphs
> >   
> >   For solutions, see https://dart.dev/go/unsound-null-safety
> > 00:05 +0 -1: Some tests failed.                                                                                                                                                                        
> > ```
> 
> Right, since source_gen is not nullsafe yet, blocked on x-y-z. The generator has to be run using `--no-sound-null-safety`. This is reflected in the test files I committed, but perhaps there is some hidden config on circleci

Please update the config file in .circleci accordingly.

**Review by vanlooverenkoen — APPROVED** [review]

**Comment by trevorwang** [comment]
close #300 

pre-release 2.0.0-beta1 has been published.

**Pull request merged**
