### PR TITLE
fix generic type with toJson method in @Body param

### PR DESCRIPTION
**Pull request by FaKenKoala**
fix: generic use toJson method in `Post` @Body when used with json_serializable annotation `genericArgumentFactories`

### CODE REVIEW

**Comment by FaKenKoala** [comment]
fix #399.

**Comment by trevorwang** [comment]
please add the test code for the generator to make sure everything is ok

**Comment by trevorwang** [comment]
@all-contributors please add @FaKenKoala  for code, example

**Comment by trevorwang** [comment]
@all-contributors please add @FaKenKoala for code, example

**Comment by trevorwang** [comment]
@all-contributors please add @FaKenKoala for code, example

**Pull request merged**
